// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Category is an object representing the database table.
type Category struct {
	ID          int32            `db:"id,pk" `
	Title       string           `db:"title" `
	Slug        string           `db:"slug" `
	Description null.Val[string] `db:"description" `
}

// CategorySlice is an alias for a slice of pointers to Category.
// This should almost always be used instead of []*Category.
type CategorySlice []*Category

// Categories contains methods to work with the categories table
var Categories = psql.NewTablex[*Category, CategorySlice, *CategorySetter]("", "categories", buildCategoryColumns("categories"))

// CategoriesQuery is a query on the categories table
type CategoriesQuery = *psql.ViewQuery[*Category, CategorySlice]

func buildCategoryColumns(alias string) categoryColumns {
	return categoryColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "title", "slug", "description",
		).WithParent("categories"),
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Title:       psql.Quote(alias, "title"),
		Slug:        psql.Quote(alias, "slug"),
		Description: psql.Quote(alias, "description"),
	}
}

type categoryColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	Title       psql.Expression
	Slug        psql.Expression
	Description psql.Expression
}

func (c categoryColumns) Alias() string {
	return c.tableAlias
}

func (categoryColumns) AliasedAs(alias string) categoryColumns {
	return buildCategoryColumns(alias)
}

// CategorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CategorySetter struct {
	ID          omit.Val[int32]      `db:"id,pk" `
	Title       omit.Val[string]     `db:"title" `
	Slug        omit.Val[string]     `db:"slug" `
	Description omitnull.Val[string] `db:"description" `
}

func (s CategorySetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if s.Slug.IsValue() {
		vals = append(vals, "slug")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	return vals
}

func (s CategorySetter) Overwrite(t *Category) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if s.Slug.IsValue() {
		t.Slug = s.Slug.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
}

func (s *CategorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Categories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 4)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Title.IsValue() {
			vals[1] = psql.Arg(s.Title.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Slug.IsValue() {
			vals[2] = psql.Arg(s.Slug.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[3] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CategorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CategorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "title")...),
			psql.Arg(s.Title),
		}})
	}

	if s.Slug.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "slug")...),
			psql.Arg(s.Slug),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	return exprs
}

// FindCategory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCategory(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*Category, error) {
	if len(cols) == 0 {
		return Categories.Query(
			sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Categories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CategoryExists checks the presence of a single record by primary key
func CategoryExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Category is retrieved from the database
func (o *Category) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, CategorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Category
func (o *Category) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Category) pkEQ() dialect.Expression {
	return psql.Quote("categories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Category
func (o *Category) Update(ctx context.Context, exec bob.Executor, s *CategorySetter) error {
	v, err := Categories.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Category record with an executor
func (o *Category) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Categories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Category using the executor
func (o *Category) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after CategorySlice is retrieved from the database
func (o CategorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CategorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("categories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CategorySlice) copyMatchingRows(from ...*Category) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CategorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterUpdateHooks on the slice
				_, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CategorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterDeleteHooks on the slice
				_, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CategorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CategorySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CategorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CategorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Categories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type categoryWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, int32]
	Title       psql.WhereMod[Q, string]
	Slug        psql.WhereMod[Q, string]
	Description psql.WhereNullMod[Q, string]
}

func (categoryWhere[Q]) AliasedAs(alias string) categoryWhere[Q] {
	return buildCategoryWhere[Q](buildCategoryColumns(alias))
}

func buildCategoryWhere[Q psql.Filterable](cols categoryColumns) categoryWhere[Q] {
	return categoryWhere[Q]{
		ID:          psql.Where[Q, int32](cols.ID),
		Title:       psql.Where[Q, string](cols.Title),
		Slug:        psql.Where[Q, string](cols.Slug),
		Description: psql.WhereNull[Q, string](cols.Description),
	}
}
