// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package enums

import (
	"database/sql/driver"
	"fmt"
)

// Enum values for UserRole
const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func AllUserRole() []UserRole {
	return []UserRole{
		UserRoleUser,
		UserRoleAdmin,
	}
}

type UserRole string

func (e UserRole) String() string {
	return string(e)
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleUser, UserRoleAdmin:
		return true
	default:
		return false
	}
}

// useful when testing in other packages
func (e UserRole) All() []UserRole {
	return AllUserRole()
}

func (e UserRole) MarshalText() ([]byte, error) {
	return []byte(e), nil
}

func (e *UserRole) UnmarshalText(text []byte) error {
	return e.Scan(text)
}

func (e UserRole) MarshalBinary() ([]byte, error) {
	return []byte(e), nil
}

func (e *UserRole) UnmarshalBinary(data []byte) error {
	return e.Scan(data)
}

func (e UserRole) Value() (driver.Value, error) {
	return string(e), nil
}

func (e *UserRole) Scan(value any) error {
	switch x := value.(type) {
	case string:
		*e = UserRole(x)
	case []byte:
		*e = UserRole(x)
	case nil:
		return fmt.Errorf("cannot nil into UserRole")
	default:
		return fmt.Errorf("cannot scan type %T: %v", value, value)
	}

	if !e.Valid() {
		return fmt.Errorf("invalid UserRole value: %s", *e)
	}

	return nil
}
