// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Categories = Table[
	categoryColumns,
	categoryIndexes,
	categoryForeignKeys,
	categoryUniques,
	categoryChecks,
]{
	Schema: "",
	Name:   "categories",
	Columns: categoryColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('categories_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Slug: column{
			Name:      "slug",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: categoryIndexes{
		CategoriesPkey: index{
			Type: "btree",
			Name: "categories_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		CategoriesSlugKey: index{
			Type: "btree",
			Name: "categories_slug_key",
			Columns: []indexColumn{
				{
					Name:         "slug",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxCategoriesSlug: index{
			Type: "btree",
			Name: "idx_categories_slug",
			Columns: []indexColumn{
				{
					Name:         "slug",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "categories_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: categoryUniques{
		CategoriesSlugKey: constraint{
			Name:    "categories_slug_key",
			Columns: []string{"slug"},
			Comment: "",
		},
	},

	Comment: "",
}

type categoryColumns struct {
	ID          column
	Title       column
	Slug        column
	Description column
}

func (c categoryColumns) AsSlice() []column {
	return []column{
		c.ID, c.Title, c.Slug, c.Description,
	}
}

type categoryIndexes struct {
	CategoriesPkey    index
	CategoriesSlugKey index
	IdxCategoriesSlug index
}

func (i categoryIndexes) AsSlice() []index {
	return []index{
		i.CategoriesPkey, i.CategoriesSlugKey, i.IdxCategoriesSlug,
	}
}

type categoryForeignKeys struct{}

func (f categoryForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type categoryUniques struct {
	CategoriesSlugKey constraint
}

func (u categoryUniques) AsSlice() []constraint {
	return []constraint{
		u.CategoriesSlugKey,
	}
}

type categoryChecks struct{}

func (c categoryChecks) AsSlice() []check {
	return []check{}
}
