// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Users = Table[
	userColumns,
	userIndexes,
	userForeignKeys,
	userUniques,
	userChecks,
]{
	Schema: "",
	Name:   "users",
	Columns: userColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('users_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Login: column{
			Name:      "login",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Fullname: column{
			Name:      "fullname",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Rating: column{
			Name:      "rating",
			DBType:    "integer",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Role: column{
			Name:      "role",
			DBType:    "public.user_role",
			Default:   "'user'::user_role",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Password: column{
			Name:      "password",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EmailVerified: column{
			Name:      "email_verified",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GoogleID: column{
			Name:      "google_id",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userIndexes{
		UsersPkey: index{
			Type: "btree",
			Name: "users_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersEmailKey: index{
			Type: "btree",
			Name: "users_email_key",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersGoogleIDKey: index{
			Type: "btree",
			Name: "users_google_id_key",
			Columns: []indexColumn{
				{
					Name:         "google_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "users_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: userUniques{
		UsersEmailKey: constraint{
			Name:    "users_email_key",
			Columns: []string{"email"},
			Comment: "",
		},
		UsersGoogleIDKey: constraint{
			Name:    "users_google_id_key",
			Columns: []string{"google_id"},
			Comment: "",
		},
	},

	Comment: "",
}

type userColumns struct {
	ID            column
	Login         column
	Email         column
	Fullname      column
	Rating        column
	Role          column
	Password      column
	CreatedAt     column
	EmailVerified column
	GoogleID      column
}

func (c userColumns) AsSlice() []column {
	return []column{
		c.ID, c.Login, c.Email, c.Fullname, c.Rating, c.Role, c.Password, c.CreatedAt, c.EmailVerified, c.GoogleID,
	}
}

type userIndexes struct {
	UsersPkey        index
	UsersEmailKey    index
	UsersGoogleIDKey index
}

func (i userIndexes) AsSlice() []index {
	return []index{
		i.UsersPkey, i.UsersEmailKey, i.UsersGoogleIDKey,
	}
}

type userForeignKeys struct{}

func (f userForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userUniques struct {
	UsersEmailKey    constraint
	UsersGoogleIDKey constraint
}

func (u userUniques) AsSlice() []constraint {
	return []constraint{
		u.UsersEmailKey, u.UsersGoogleIDKey,
	}
}

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{}
}
