// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/RofaBR/Go-Usof/internal/models"
	enums "github.com/RofaBR/Go-Usof/internal/models/enums"
	"github.com/aarondl/opt/null"
)

type Factory struct {
	baseCategoryMods        CategoryModSlice
	baseSchemaMigrationMods SchemaMigrationModSlice
	baseUserMods            UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewCategory(mods ...CategoryMod) *CategoryTemplate {
	return f.NewCategoryWithContext(context.Background(), mods...)
}

func (f *Factory) NewCategoryWithContext(ctx context.Context, mods ...CategoryMod) *CategoryTemplate {
	o := &CategoryTemplate{f: f}

	if f != nil {
		f.baseCategoryMods.Apply(ctx, o)
	}

	CategoryModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCategory(m *models.Category) *CategoryTemplate {
	o := &CategoryTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Title = func() string { return m.Title }
	o.Slug = func() string { return m.Slug }
	o.Description = func() null.Val[string] { return m.Description }

	return o
}

func (f *Factory) NewSchemaMigration(mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	return f.NewSchemaMigrationWithContext(context.Background(), mods...)
}

func (f *Factory) NewSchemaMigrationWithContext(ctx context.Context, mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f}

	if f != nil {
		f.baseSchemaMigrationMods.Apply(ctx, o)
	}

	SchemaMigrationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSchemaMigration(m *models.SchemaMigration) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f, alreadyPersisted: true}

	o.Version = func() int64 { return m.Version }
	o.Dirty = func() bool { return m.Dirty }

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Login = func() string { return m.Login }
	o.Email = func() string { return m.Email }
	o.Fullname = func() string { return m.Fullname }
	o.Rating = func() int32 { return m.Rating }
	o.Role = func() enums.UserRole { return m.Role }
	o.Password = func() string { return m.Password }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.EmailVerified = func() bool { return m.EmailVerified }
	o.GoogleID = func() null.Val[string] { return m.GoogleID }

	return o
}

func (f *Factory) ClearBaseCategoryMods() {
	f.baseCategoryMods = nil
}

func (f *Factory) AddBaseCategoryMod(mods ...CategoryMod) {
	f.baseCategoryMods = append(f.baseCategoryMods, mods...)
}

func (f *Factory) ClearBaseSchemaMigrationMods() {
	f.baseSchemaMigrationMods = nil
}

func (f *Factory) AddBaseSchemaMigrationMod(mods ...SchemaMigrationMod) {
	f.baseSchemaMigrationMods = append(f.baseSchemaMigrationMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
