// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	models "github.com/RofaBR/Go-Usof/internal/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type CategoryMod interface {
	Apply(context.Context, *CategoryTemplate)
}

type CategoryModFunc func(context.Context, *CategoryTemplate)

func (f CategoryModFunc) Apply(ctx context.Context, n *CategoryTemplate) {
	f(ctx, n)
}

type CategoryModSlice []CategoryMod

func (mods CategoryModSlice) Apply(ctx context.Context, n *CategoryTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CategoryTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CategoryTemplate struct {
	ID          func() int32
	Title       func() string
	Slug        func() string
	Description func() null.Val[string]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the CategoryTemplate
func (o *CategoryTemplate) Apply(ctx context.Context, mods ...CategoryMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Category
// according to the relationships in the template. Nothing is inserted into the db
func (t CategoryTemplate) setModelRels(o *models.Category) {}

// BuildSetter returns an *models.CategorySetter
// this does nothing with the relationship templates
func (o CategoryTemplate) BuildSetter() *models.CategorySetter {
	m := &models.CategorySetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Title != nil {
		val := o.Title()
		m.Title = omit.From(val)
	}
	if o.Slug != nil {
		val := o.Slug()
		m.Slug = omit.From(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.CategorySetter
// this does nothing with the relationship templates
func (o CategoryTemplate) BuildManySetter(number int) []*models.CategorySetter {
	m := make([]*models.CategorySetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Category
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CategoryTemplate.Create
func (o CategoryTemplate) Build() *models.Category {
	m := &models.Category{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.Slug != nil {
		m.Slug = o.Slug()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CategorySlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CategoryTemplate.CreateMany
func (o CategoryTemplate) BuildMany(number int) models.CategorySlice {
	m := make(models.CategorySlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCategory(m *models.CategorySetter) {
	if !(m.Title.IsValue()) {
		val := random_string(nil, "255")
		m.Title = omit.From(val)
	}
	if !(m.Slug.IsValue()) {
		val := random_string(nil, "255")
		m.Slug = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Category
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CategoryTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Category) error {
	var err error

	return err
}

// Create builds a category and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CategoryTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Category, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCategory(opt)

	m, err := models.Categories.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a category and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CategoryTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Category {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a category and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CategoryTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Category {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple categories and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CategoryTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CategorySlice, error) {
	var err error
	m := make(models.CategorySlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple categories and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CategoryTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CategorySlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple categories and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CategoryTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CategorySlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Category has methods that act as mods for the CategoryTemplate
var CategoryMods categoryMods

type categoryMods struct{}

func (m categoryMods) RandomizeAllColumns(f *faker.Faker) CategoryMod {
	return CategoryModSlice{
		CategoryMods.RandomID(f),
		CategoryMods.RandomTitle(f),
		CategoryMods.RandomSlug(f),
		CategoryMods.RandomDescription(f),
	}
}

// Set the model columns to this value
func (m categoryMods) ID(val int32) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m categoryMods) IDFunc(f func() int32) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m categoryMods) UnsetID() CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m categoryMods) RandomID(f *faker.Faker) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m categoryMods) Title(val string) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m categoryMods) TitleFunc(f func() string) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m categoryMods) UnsetTitle() CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m categoryMods) RandomTitle(f *faker.Faker) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Title = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m categoryMods) Slug(val string) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Slug = func() string { return val }
	})
}

// Set the Column from the function
func (m categoryMods) SlugFunc(f func() string) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Slug = f
	})
}

// Clear any values for the column
func (m categoryMods) UnsetSlug() CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Slug = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m categoryMods) RandomSlug(f *faker.Faker) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Slug = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m categoryMods) Description(val null.Val[string]) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Description = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m categoryMods) DescriptionFunc(f func() null.Val[string]) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m categoryMods) UnsetDescription() CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m categoryMods) RandomDescription(f *faker.Faker) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m categoryMods) RandomDescriptionNotNull(f *faker.Faker) CategoryMod {
	return CategoryModFunc(func(_ context.Context, o *CategoryTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m categoryMods) WithParentsCascading() CategoryMod {
	return CategoryModFunc(func(ctx context.Context, o *CategoryTemplate) {
		if isDone, _ := categoryWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = categoryWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
