// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/RofaBR/Go-Usof/internal/models"
	enums "github.com/RofaBR/Go-Usof/internal/models/enums"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type UserMod interface {
	Apply(context.Context, *UserTemplate)
}

type UserModFunc func(context.Context, *UserTemplate)

func (f UserModFunc) Apply(ctx context.Context, n *UserTemplate) {
	f(ctx, n)
}

type UserModSlice []UserMod

func (mods UserModSlice) Apply(ctx context.Context, n *UserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserTemplate struct {
	ID            func() int64
	Login         func() string
	Email         func() string
	Fullname      func() string
	Rating        func() int32
	Role          func() enums.UserRole
	Password      func() string
	CreatedAt     func() time.Time
	EmailVerified func() bool
	GoogleID      func() null.Val[string]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the UserTemplate
func (o *UserTemplate) Apply(ctx context.Context, mods ...UserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.User
// according to the relationships in the template. Nothing is inserted into the db
func (t UserTemplate) setModelRels(o *models.User) {}

// BuildSetter returns an *models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildSetter() *models.UserSetter {
	m := &models.UserSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Login != nil {
		val := o.Login()
		m.Login = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Fullname != nil {
		val := o.Fullname()
		m.Fullname = omit.From(val)
	}
	if o.Rating != nil {
		val := o.Rating()
		m.Rating = omit.From(val)
	}
	if o.Role != nil {
		val := o.Role()
		m.Role = omit.From(val)
	}
	if o.Password != nil {
		val := o.Password()
		m.Password = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.EmailVerified != nil {
		val := o.EmailVerified()
		m.EmailVerified = omit.From(val)
	}
	if o.GoogleID != nil {
		val := o.GoogleID()
		m.GoogleID = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildManySetter(number int) []*models.UserSetter {
	m := make([]*models.UserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.User
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.Create
func (o UserTemplate) Build() *models.User {
	m := &models.User{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Login != nil {
		m.Login = o.Login()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Fullname != nil {
		m.Fullname = o.Fullname()
	}
	if o.Rating != nil {
		m.Rating = o.Rating()
	}
	if o.Role != nil {
		m.Role = o.Role()
	}
	if o.Password != nil {
		m.Password = o.Password()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.EmailVerified != nil {
		m.EmailVerified = o.EmailVerified()
	}
	if o.GoogleID != nil {
		m.GoogleID = o.GoogleID()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.CreateMany
func (o UserTemplate) BuildMany(number int) models.UserSlice {
	m := make(models.UserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUser(m *models.UserSetter) {
	if !(m.Login.IsValue()) {
		val := random_string(nil, "255")
		m.Login = omit.From(val)
	}
	if !(m.Email.IsValue()) {
		val := random_string(nil, "255")
		m.Email = omit.From(val)
	}
	if !(m.Fullname.IsValue()) {
		val := random_string(nil, "255")
		m.Fullname = omit.From(val)
	}
	if !(m.Password.IsValue()) {
		val := random_string(nil, "255")
		m.Password = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.User
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.User) error {
	var err error

	return err
}

// Create builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.User, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUser(opt)

	m, err := models.Users.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.User {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.User {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserSlice, error) {
	var err error
	m := make(models.UserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// User has methods that act as mods for the UserTemplate
var UserMods userMods

type userMods struct{}

func (m userMods) RandomizeAllColumns(f *faker.Faker) UserMod {
	return UserModSlice{
		UserMods.RandomID(f),
		UserMods.RandomLogin(f),
		UserMods.RandomEmail(f),
		UserMods.RandomFullname(f),
		UserMods.RandomRating(f),
		UserMods.RandomRole(f),
		UserMods.RandomPassword(f),
		UserMods.RandomCreatedAt(f),
		UserMods.RandomEmailVerified(f),
		UserMods.RandomGoogleID(f),
	}
}

// Set the model columns to this value
func (m userMods) ID(val int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m userMods) IDFunc(f func() int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Login(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Login = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) LoginFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Login = f
	})
}

// Clear any values for the column
func (m userMods) UnsetLogin() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Login = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomLogin(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Login = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) Email(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) EmailFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m userMods) UnsetEmail() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomEmail(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) Fullname(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Fullname = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) FullnameFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Fullname = f
	})
}

// Clear any values for the column
func (m userMods) UnsetFullname() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Fullname = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomFullname(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Fullname = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) Rating(val int32) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rating = func() int32 { return val }
	})
}

// Set the Column from the function
func (m userMods) RatingFunc(f func() int32) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rating = f
	})
}

// Clear any values for the column
func (m userMods) UnsetRating() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rating = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomRating(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rating = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Role(val enums.UserRole) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Role = func() enums.UserRole { return val }
	})
}

// Set the Column from the function
func (m userMods) RoleFunc(f func() enums.UserRole) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Role = f
	})
}

// Clear any values for the column
func (m userMods) UnsetRole() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Role = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomRole(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Role = func() enums.UserRole {
			return random_enums_UserRole(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Password(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) PasswordFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = f
	})
}

// Clear any values for the column
func (m userMods) UnsetPassword() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomPassword(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) CreatedAt(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) CreatedAtFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetCreatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomCreatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) EmailVerified(val bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.EmailVerified = func() bool { return val }
	})
}

// Set the Column from the function
func (m userMods) EmailVerifiedFunc(f func() bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.EmailVerified = f
	})
}

// Clear any values for the column
func (m userMods) UnsetEmailVerified() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.EmailVerified = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomEmailVerified(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.EmailVerified = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) GoogleID(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) GoogleIDFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetGoogleID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomGoogleID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomGoogleIDNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

func (m userMods) WithParentsCascading() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		if isDone, _ := userWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
